version: 2

project_name: actup

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch
  groups:
    - title: Features
      regexp: '^.*?feat(\\([\\w\\s]+\\))?!?:.+$'
      order: 0
    - title: Bug fixes
      regexp: '^.*?fix(\\([\\w\\s]+\\))?!?:.+$'
      order: 1
    - title: Improvements
      regexp: '^.*?refactor(\\([\\w\\s]+\\))?!?:.+$'
      order: 2

release:
  github:
    owner: lynicis
    name: actup
  draft: false
  prerelease: auto

nfpms:
  - id: packages
    package_name: actup
    vendor: Emre Sırmalı
    homepage: https://github.com/lynicis/actup
    maintainer: Emre Sırmalı <emresir94@gmail.com>
    description: Upgrade GitHub Actions versions interactively from your terminal
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/local/bin

homebrew_casks:
  - name: actup
    repository:
      owner: lynicis
      name: homebrew-tap
      branch: main
      token: '{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}'
    commit_msg_template: "Brew cask update for {{ .ProjectName }} version {{ .Tag }}"
    homepage: https://github.com/lynicis/actup
    description: Upgrade GitHub Actions versions interactively from your terminal
    url:
      verified: github.com/lynicis/actup
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/actup"]
          end

scoops:
  - name: actup
    repository:
      owner: lynicis
      name: scoop-bucket
      branch: main
      token: '{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}'
    commit_msg_template: "Scoop manifest update for {{ .ProjectName }} version {{ .Tag }}"
    homepage: https://github.com/lynicis/actup
    description: Upgrade GitHub Actions versions interactively from your terminal

snapshot:
  version_template: "{{ .Version }}-{{ .ShortCommit }}"

dist: dist
